version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio
    ports:
      - "5000:80"
    depends_on:
      - dbmysql
    command: bash -c "dotnet ef database update --context AppDbContext && dotnet run"

  dbmysql:
    image: mysql
    restart: unless-stopped
    container_name: containermysql
    environment:
      MYSQL_DATABASE: desafio
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: novo
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
      
